package seeds

import (
	"career-paths/entities"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func workPersonalitySeeder(db *gorm.DB) Seed {
	seeds := []entities.WorkPersonality{
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INTJ",
			Profession1:                "Computer Programmers",
			Description:                "Computer programmer menulis, memodifikasi, dan menguji kode dan skrip yang memungkinkan perangkat lunak dan aplikasi komputer berfungsi dengan baik. Jika produk tidak bekerja dengan benar, programmer memeriksa kode atau skrip untuk mencari kesalahan dan memodifikasinya",
			DutiesandResponsibilities1: "Membuat program dalam berbagai bahasa komputer, seperti C++, Java dan lainnya",
			DutiesandResponsibilities2: "Memperbarui dan mengembangkan program yang sudah ada",
			DutiesandResponsibilities3: "Menguji program untuk mencari kesalahan dan memperbaiki baris kode komputer yang salah",
			DutiesandResponsibilities4: "Membuat, memodifikasi, dan menguji kode atau skrip dalam perangkat lunak yang menyederhanakan pengembangan",
			Competition:                "Object Oriented Programming , HTML CSS, Rest Apis, Software Development, Java, Javascript, Python, Mobile Developer, UI UX Design, Fullstack Developer",
			Subject:                    "Pemorgraman Mobile Lanjut",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INTJ",
			Profession2:                "Computer Network Architects",
			Description:                "Merancang dan membangun jaringan komunikasi data, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), dan Intranet harus memiliki pengetahuan yang luas tentang rencana bisnis organisasi untuk merancang jaringan yang dapat membantu organisasi mencapai tujuannya",
			DutiesandResponsibilities1: "Membuat rencana dan tata letak untuk jaringan komunikasi data",
			DutiesandResponsibilities2: "Mempresentasikan rencana kepada manajemen dan menjelaskan mengapa rencana tersebut merupakan kepentingan terbaik organisasi untuk dilaksanakan",
			DutiesandResponsibilities3: "Meningkatkan perangkat keras, seperti router atau adaptor, dan perangkat lunak, seperti driver jaringan, sesuai kebutuhan untuk mendukung jaringan komputer",
			DutiesandResponsibilities4: "Meneliti teknologi jaringan baru untuk menentukan apa yang terbaik untuk mendukung organisasi mereka di masa depan",
			Competition:                "Net Engineer, Net Security, Red Hat, Net Infrastructure, Solution Architect, Router Switch, Architecture Design, Cloud Technology, Azure, Devops, Cloud Technology,  Deploy Functional, Net, Lan, Wlan",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INTJ",
			Profession3:                "Computer And Information Reserch Scientists",
			Description:                "Merancang penggunaan inovatif untuk teknologi baru dan yang sudah ada, mempelajari dan memecahkan masalah kompleks dalam komputasi untuk bisnis, sains, kedokteran, dan bidang lainnya",
			DutiesandResponsibilities1: "Mengeksplorasi masalah dalam komputasi dan mengembangkan teori dan model untuk mengatasi masalah",
			DutiesandResponsibilities2: "Berkolaborasi dengan para ilmuwan dan engineers untuk memecahkan masalah komputasi yang kompleks",
			DutiesandResponsibilities3: "Mengembangkan bahasa komputasi baru, sistem perangkat lunak, dan alat bantu lainnya untuk meningkatkan cara orang bekerja dengan komputer",
			DutiesandResponsibilities4: "Merancang dan melakukan eksperimen untuk menguji pengoperasian sistem perangkat lunak, sering kali menggunakan teknik dari data science dan machine learning",
			DutiesandResponsibilities5: "Menganalisis hasil eksperimen mereka",
			Competition:                "Data Science, Data Scientist, Machine Learning, Data Analysis, Data management , Data Visualization",
			Subject:                    "Data Mining dan Warehousing, Pengantar Data Science, Embedded System, Soft Computing,, Programmable Logic Controller, Big Data Energi Ketenagalistrikan, Dataset Develompent, Mikrocontroller",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INTP",
			Profession1:                "Computer And Information Research Scientists",
			Description:                "Merancang penggunaan inovatif untuk teknologi baru dan yang sudah ada, mempelajari dan memecahkan masalah kompleks dalam komputasi untuk bisnis, sains, kedokteran, dan bidang lainnya",
			DutiesandResponsibilities1: "Mengeksplorasi masalah dalam komputasi dan mengembangkan teori dan model untuk mengatasi masalah",
			DutiesandResponsibilities2: "Berkolaborasi dengan para ilmuwan dan engineers untuk memecahkan masalah komputasi yang kompleks",
			DutiesandResponsibilities3: "Mengembangkan bahasa komputasi baru, sistem perangkat lunak, dan alat bantu lainnya untuk meningkatkan cara orang bekerja dengan komputer",
			DutiesandResponsibilities4: "Merancang dan melakukan eksperimen untuk menguji pengoperasian sistem perangkat lunak, sering kali menggunakan teknik dari data science dan machine learning",
			DutiesandResponsibilities5: "Menganalisis hasil eksperimen mereka",
			Competition:                "Data Science, Data Scientist, Machine Learning, Data Analysis, Data management , Data Visualization",
			Subject:                    "Data Mining dan Warehousing, Pengantar Data Science, Embedded System, Soft Computing,, Programmable Logic Controller, Big Data Energi Ketenagalistrikan, Dataset Develompent, Mikrocontroller",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INFJ",
			Profession1:                "Web Developer and Digital Designers",
			Description:                "Web developers membuat dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya",
			DutiesandResponsibilities1: "Bertemu dengan klien atau manajemen untuk mendiskusikan kebutuhan, desain, dan  fungsionalitas situs web atau antarmuka",
			DutiesandResponsibilities2: "Membuat dan menguji aplikasi, antarmuka, dan menu navigasi untuk situs web",
			DutiesandResponsibilities3: "Bekerja dengan desainer grafis dan desainer lain untuk menentukan tata letak situs web",
			DutiesandResponsibilities4: "Merancang dan mengembangkan grafis dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			Competition:                "HTML CSS, Javascript Framework, Rest Apis, SQL Server, UI UX, PHP Laravel, Laravel Node, PHP Javascript.",
			Subject:                    "Pemrograman Web Lanjut",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INFJ",
			Profession2:                "Software Developer , Quality Assurance Analysts, and Testers",
			Description:                "Software Developer Membuat aplikasi komputer yang memungkinkan pengguna melakukan tugas tertentu dan sistem yang mendasari berjalannya perangkat lunak atau mengontrol jaringan. Quality Assurance and Tester Merancang dan melaksanakan pengujian perangkat lunak untuk mengidentifikasi masalah dan mempelajari cara kerja perangkat lunak.",
			DutiesandResponsibilities1: "Menganalisis kebutuhan pengguna, merancang dan mengembangkan perangkat lunak untuk memenuhi kebutuhan tersebut",
			DutiesandResponsibilities2: "Merancang setiap bagian dari aplikasi atau sistem dan merencanakan bagaimana bagian-bagian tersebut dapat bekerja bersama",
			DutiesandResponsibilities3: "Membuat berbagai model dan diagram yang menunjukkan kepada programmer perangkat lunak yang diperlukan untuk suatu aplikasi",
			DutiesandResponsibilities4: "Mengidentifikasi risiko proyek dan merekomendasikan langkah-langkah untuk meminimalkan risiko tersebut",
			DutiesandResponsibilities5: "Menguji Software",
			Competition:                "Software Testing,Test Automation,Quality Assurance, Software Development, Project Management, Product Management,Python, Java Spring Frameworks",
			Subject:                    "Manajemen Proyek Perangkat Lunak , Software Quality and Metric",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "INFP",
			Profession1:                "Computer Support Specialists",
			Description:                "Membantu pengguna komputer, organisasi, memelihara jaringan komputer atau memberikan bantuan teknis secara langsung kepada pengguna komputer serta menganalisis, memecahkan masalah, dan memelihara jaringan komputer.",
			DutiesandResponsibilities1: "Menguji dan mengevaluasi sistem jaringan yang ada",
			DutiesandResponsibilities2: "Menganalisis masalah komputer pelanggan untuk mendiagnosis dan menentukan penyebabnya",
			DutiesandResponsibilities3: "Mendokumentasikan deskripsi pelanggan tentang masalah komputer mereka",
			DutiesandResponsibilities4: "Memandu pelanggan melalui langkah-langkah pemecahan masalah yang direkomendasikan",
			Competition:                "Hardware, Software, Technical Support, Application Support, Computer System, Computer Hardware, Computer Net, Lan Wan, Net Problem, Installation Configuration, Education Computer",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTJ",
			Profession1:                "Computer and Information Research Scientist",
			Description:                "Merancang penggunaan inovatif untuk teknologi baru dan yang sudah ada, mempelajari dan memecahkan masalah kompleks dalam komputasi untuk bisnis, sains, kedokteran, dan bidang lainnya.",
			DutiesandResponsibilities1: "Mengeksplorasi masalah dalam komputasi dan mengembangkan teori dan model untuk mengatasi masalah",
			DutiesandResponsibilities2: "Berkolaborasi dengan para ilmuwan dan engineers untuk memecahkan masalah komputasi yang kompleks",
			DutiesandResponsibilities3: "Mengembangkan bahasa komputasi baru, sistem perangkat lunak, dan alat bantu lainnya untuk meningkatkan cara orang bekerja dengan komputer",
			DutiesandResponsibilities4: "Merancang dan melakukan eksperimen untuk menguji pengoperasian sistem perangkat lunak, sering kali menggunakan teknik dari data science dan machine learning",
			DutiesandResponsibilities5: "Menganalisis hasil eksperimen mereka",
			Competition:                "Data Science, Data Scientist, Machine Learning, Data Analysis, Data management , Data Visualization",
			Subject:                    "Data Mining dan Warehousing, Pengantar Data Science, Embedded System, Soft Computing,, Programmable Logic Controller, Big Data Energi Ketenagalistrikan, Dataset Develompent, Mikrocontroller",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTJ",
			Profession2:                "Software Developer , Quality Assurance Analysts, and Testers",
			Description:                "Software Developer Membuat aplikasi komputer yang memungkinkan pengguna melakukan tugas tertentu dan sistem yang mendasari berjalannya perangkat lunak atau mengontrol jaringan. Quality Assurance Tester Merancang dan melaksanakan pengujian perangkat lunak untuk mengidentifikasi masalah dan mempelajari cara kerja perangkat lunak.",
			DutiesandResponsibilities1: "Menganalisis kebutuhan pengguna, merancang dan mengembangkan perangkat lunak untuk memenuhi kebutuhan tersebut",
			DutiesandResponsibilities2: "Merancang setiap bagian dari aplikasi atau sistem dan merencanakan bagaimana bagian-bagian tersebut dapat bekerja bersama",
			DutiesandResponsibilities3: "Membuat berbagai model dan diagram yang menunjukkan kepada programmer perangkat lunak yang diperlukan untuk suatu aplikasi",
			DutiesandResponsibilities4: "Mengidentifikasi risiko proyek dan merekomendasikan langkah-langkah untuk meminimalkan risiko tersebut",
			DutiesandResponsibilities5: "Menguji software",
			Competition:                "Software Testing,Test Automation,Quality Assurance, Software Development, Project Management, Product Management,Python, Java Spring Frameworks.",
			Subject:                    "Manajemen Proyek Perangkat Lunak , Software Quality and Metric",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTJ",
			Profession3:                "Database Administrators and Architects",
			Description:                "Membuat atau mengatur sistem untuk menyimpan dan mengamankan berbagai data, seperti informasi keuangan dan catatan pengiriman pelanggan. Memastikan bahwa data tersebut tersedia bagi pengguna yang berwenang.",
			DutiesandResponsibilities1: "Mengidentifikasi kebutuhan pengguna untuk membuat dan mengelola database",
			DutiesandResponsibilities2: "Merancang dan membangun basis data baru",
			DutiesandResponsibilities3: "Membuat dan menguji modifikasi pada struktur basis data bila diperlukan",
			DutiesandResponsibilities4: "Memelihara basis data dan memperbarui izin update",
			Competition:                "Database Administrator, SQL Server, Database Design, Backup Recovery, Backup Restore, Database System, Database Management.",
			Subject:                    "Optimasi Basis Data, Basis Data Lanjut, Sistem Informasi Geografis Energi Ketenagalistrikan",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTJ",
			Profession4:                "Computer Network Architects",
			Description:                "Merancang dan membangun jaringan komunikasi data, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), dan Intranet harus memiliki pengetahuan yang luas tentang rencana bisnis organisasi untuk merancang jaringan yang dapat membantu organisasi mencapai tujuannya.",
			DutiesandResponsibilities1: "Membuat rencana dan tata letak untuk jaringan komunikasi data",
			DutiesandResponsibilities2: "Mempresentasikan rencana kepada manajemen dan menjelaskan mengapa rencana tersebut merupakan kepentingan terbaik organisasi untuk dilaksanakan",
			DutiesandResponsibilities3: "Meningkatkan perangkat keras, seperti router atau adaptor, dan perangkat lunak, seperti driver jaringan, sesuai kebutuhan untuk mendukung jaringan komputer",
			DutiesandResponsibilities4: "Meneliti teknologi jaringan baru untuk menentukan apa yang terbaik untuk mendukung organisasi mereka di masa depan",
			Competition:                "Net Engineer, Net Security, Red Hat, Net Infrastructure, Solution Architect, Router Switch, Architecture Design, Cloud Technology, Azure, Devops, Cloud Technology,  Deploy Functional, Net, Lan, Wlan",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTP",
			Profession1:                "Computer And Information Reserch Scientists",
			Description:                "Merancang penggunaan inovatif untuk teknologi baru dan yang sudah ada, mempelajari dan memecahkan masalah kompleks dalam komputasi untuk bisnis, sains, kedokteran, dan bidang lainnya.",
			DutiesandResponsibilities1: "Mengeksplorasi masalah dalam komputasi dan mengembangkan teori dan model untuk mengatasi masalah",
			DutiesandResponsibilities2: "Berkolaborasi dengan para ilmuwan dan engineers untuk memecahkan masalah komputasi yang kompleks",
			DutiesandResponsibilities3: "Mengembangkan bahasa komputasi baru, sistem perangkat lunak, dan alat bantu lainnya untuk meningkatkan cara orang bekerja dengan komputer",
			DutiesandResponsibilities4: "Merancang dan melakukan eksperimen untuk menguji pengoperasian sistem perangkat lunak, sering kali menggunakan teknik dari data science dan machine learning",
			DutiesandResponsibilities5: "Menganalisis hasil eksperimen mereka",
			Competition:                "Data Science, Data Scientist, Machine Learning, Data Analysis, Data management , Data Visualization",
			Subject:                    "Data Mining dan Warehousing, Pengantar Data Science, Embedded System, Soft Computing,, Programmable Logic Controller, Big Data Energi Ketenagalistrikan, Dataset Develompent, Mikrocontroller",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISTP",
			Profession2:                "Network and Computer System Administrator",
			Description:                "Bertanggung jawab atas pengoperasian jaringan sehari-hari. Mengatur, memasang, dan mendukung sistem komputer organisasi, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), segmen jaringan, intranet, dan sistem komunikasi data lainnya masalah server komputer",
			DutiesandResponsibilities1: "Menjaga keamanan jaringan dan sistem komputer",
			DutiesandResponsibilities2: "Mengevaluasi dan mengoptimalkan kinerja jaringan atau sistem",
			DutiesandResponsibilities3: "Melatih pengguna dalam penggunaan perangkat keras dan perangkat lunak yang tepat",
			DutiesandResponsibilities4: "Menafsirkan dan memecahkan masalah ketika pengguna atau sistem pemantauan otomatis memberi tahu mereka bahwa ada masalah",
			Competition:                "Network Engineer, System Administrator, Operate System,  Hardware, Software, Network Administrator, Computer Network, Router Switch, Server Network, System Security",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISFJ",
			Profession1:                "Network and Computer System Administrator",
			Description:                "Bertanggung jawab atas pengoperasian jaringan sehari-hari. Mengatur, memasang, dan mendukung sistem komputer organisasi, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), segmen jaringan, intranet, dan sistem komunikasi data lainnya masalah server komputer.",
			DutiesandResponsibilities1: "Menjaga keamanan jaringan dan sistem komputer",
			DutiesandResponsibilities2: "Mengevaluasi dan mengoptimalkan kinerja jaringan atau sistem",
			DutiesandResponsibilities3: "Melatih pengguna dalam penggunaan perangkat keras dan perangkat lunak yang tepat",
			DutiesandResponsibilities4: "Menafsirkan dan memecahkan masalah ketika pengguna atau sistem pemantauan otomatis memberi tahu mereka bahwa ada masalah",
			Competition:                "Network Engineer, System Administrator, Operate System,  Hardware, Software, Network Administrator, Computer Network, Router Switch, Server Network, System Security",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISFP",
			Profession1:                "Computer Support Specialists",
			Description:                "Membantu pengguna komputer, organisasi, memelihara jaringan komputer atau memberikan bantuan teknis secara langsung kepada pengguna komputer serta menganalisis, memecahkan masalah, dan memelihara jaringan komputer.",
			DutiesandResponsibilities1: "Menguji dan mengevaluasi sistem jaringan yang ada",
			DutiesandResponsibilities2: "Menganalisis masalah komputer pelanggan untuk mendiagnosis dan menentukan penyebabnya",
			DutiesandResponsibilities3: "Mendokumentasikan deskripsi pelanggan tentang masalah komputer mereka",
			DutiesandResponsibilities4: "Memandu pelanggan melalui langkah-langkah pemecahan masalah yang direkomendasikan",
			Competition:                "Hardware, Software, Technical Support, Application Support, Computer System, Computer Hardware, Computer Net, Lan Wan, Net Problem, Installation Configuration, Education Computer",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ISFP",
			Profession2:                "Information Security Analysts",
			Description:                "Merencanakan dan melaksanakan langkah-langkah keamanan untuk melindungi jaringan, sistem komputer organisasi dan memasang perangkat lunak seperti firewall untuk melindungi jaringan komputer",
			DutiesandResponsibilities1: "Memeriksa kerentanan pada sistem komputer dan jaringan",
			DutiesandResponsibilities2: "Meneliti tren keamanan teknologi informasi (TI) terbaru",
			DutiesandResponsibilities3: "Menyiapkan laporan yang mendokumentasikan metrik umum, percobaan serangan, dan pelanggaran keamanan",
			DutiesandResponsibilities4: "Mengembangkan standar keamanan dan praktik terbaik untuk organisasi mereka",
			DutiesandResponsibilities5: "Membantu pengguna komputer saat mereka perlu menginstal atau mempelajari produk dan prosedur keamanan baru",
			Competition:                "Information Security, Cyber Security, Net Security, Application SecuritySecurity Engineer, Infrastructure Security, Osi Layer, Security Analyst",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENTJ",
			Profession1:                "Web Developer and Digital Designers",
			Description:                "Web developers membuat dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			DutiesandResponsibilities1: "Bertemu dengan klien atau manajemen untuk mendiskusikan kebutuhan, desain, dan  fungsionalitas situs web atau antarmuka",
			DutiesandResponsibilities2: "Membuat dan menguji aplikasi, antarmuka, dan menu navigasi untuk situs web",
			DutiesandResponsibilities3: "Bekerja dengan desainer grafis dan desainer lain untuk menentukan tata letak situs web",
			DutiesandResponsibilities4: "Merancang dan mengembangkan grafis dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			Competition:                "HTML CSS, Javascript Framework, Rest Apis, SQL Server, UI UX, PHP Laravel, Laravel Node, PHP Javascript",
			Subject:                    "Pemrograman Web Lanjut",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENTJ",
			Profession2:                "Software Developer , Quality Assurance Analysts, and Testers",
			Description:                "SD Membuat aplikasi komputer yang memungkinkan pengguna melakukan tugas tertentu dan sistem yang mendasari berjalannya perangkat lunak atau mengontrol jaringan. QAT Merancang dan melaksanakan pengujian perangkat lunak untuk mengidentifikasi masalah dan mempelajari cara kerja perangkat lunak.",
			DutiesandResponsibilities1: "Menganalisis kebutuhan pengguna, merancang dan mengembangkan perangkat lunak untuk memenuhi kebutuhan tersebut",
			DutiesandResponsibilities2: "Merancang setiap bagian dari aplikasi atau sistem dan merencanakan bagaimana bagian-bagian tersebut dapat bekerja bersama",
			DutiesandResponsibilities3: "Membuat berbagai model dan diagram yang menunjukkan kepada programmer perangkat lunak yang diperlukan untuk suatu aplikasi",
			DutiesandResponsibilities4: "Mengidentifikasi risiko proyek dan merekomendasikan langkah-langkah untuk meminimalkan risiko tersebut",
			DutiesandResponsibilities5: "Menguji software",
			Competition:                "Software Testing,Test Automation,Quality Assurance, Software Development, Project Management, Product Management,Python, Java Spring Frameworks.",
			Subject:                    "Manajemen Proyek Perangkat Lunak , Software Quality and Metric",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENTP",
			Profession1:                "Computer System Analysis",
			Description:                "mempelajari sistem prosedur komputer organisasi dan merancang peningkatannya. membantu organisasi beroperasi dengan lebih efisien dan membuat diagram untuk membantu programmer dan arsitek membangun sistem komputer",
			DutiesandResponsibilities1: "Menganalisis biaya dan manfaat sistem TI dan peningkatan untuk membantu manajer memutuskan mana yang akan dipasang, jika ada",
			DutiesandResponsibilities2: "Merancang cara untuk menambahkan fungsionalitas ke sistem komputer yang sudah ada",
			DutiesandResponsibilities3: "Merancang sistem baru dengan mengonfigurasi perangkat keras dan perangkat lunak",
			DutiesandResponsibilities4: "Mengawasi instalasi dan konfigurasi sistem baru dan menyesuaikannya untuk organisasi",
			DutiesandResponsibilities5: "Menguji sistem untuk memastikan bahwa sistem tersebut bekerja seperti yang diharapkan",
			DutiesandResponsibilities6: "Menulis instruksi manual dan melatih pengguna akhir sistem",
			Competition:                "Business Analysis, Data Analysis, Project Management, System Analysis, Analytical Skills, Data Visualization, Agile Project Management",
			Subject:                    "Sistem Informasi Geografis Energi Ketenagalistrikan",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENFJ",
			Profession1:                "Web Developer and Digital Designers",
			Description:                "Web developers membuat dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			DutiesandResponsibilities1: "Bertemu dengan klien atau manajemen untuk mendiskusikan kebutuhan, desain, dan  fungsionalitas situs web atau antarmuka",
			DutiesandResponsibilities2: "Membuat dan menguji aplikasi, antarmuka, dan menu navigasi untuk situs web",
			DutiesandResponsibilities3: "Bekerja dengan desainer grafis dan desainer lain untuk menentukan tata letak situs web",
			DutiesandResponsibilities4: "Merancang dan mengembangkan grafis dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			Competition:                "HTML CSS, Javascript Framework, Rest Apis, SQL Server, UI UX, PHP Laravel, Laravel Node, PHP Javascript",
			Subject:                    "Pemrograman Web Lanjut",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENFJ",
			Profession2:                "Software Developer , Quality Assurance Analysts, and Testers",
			Description:                "SD Membuat aplikasi komputer yang memungkinkan pengguna melakukan tugas tertentu dan sistem yang mendasari berjalannya perangkat lunak atau mengontrol jaringan. QAT Merancang dan melaksanakan pengujian perangkat lunak untuk mengidentifikasi masalah dan mempelajari cara kerja perangkat lunak.",
			DutiesandResponsibilities1: "Menganalisis kebutuhan pengguna, merancang dan mengembangkan perangkat lunak untuk memenuhi kebutuhan tersebut",
			DutiesandResponsibilities2: "Merancang setiap bagian dari aplikasi atau sistem dan merencanakan bagaimana bagian-bagian tersebut dapat bekerja bersama",
			DutiesandResponsibilities3: "Membuat berbagai model dan diagram yang menunjukkan kepada programmer perangkat lunak yang diperlukan untuk suatu aplikasi",
			DutiesandResponsibilities4: "Mengidentifikasi risiko proyek dan merekomendasikan langkah-langkah untuk meminimalkan risiko tersebut",
			DutiesandResponsibilities5: "Menguji software",
			Competition:                "Software Testing,Test Automation,Quality Assurance, Software Development, Project Management, Product Management,Python, Java Spring Frameworks.",
			Subject:                    "Manajemen Proyek Perangkat Lunak , Software Quality and Metric",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ENFP",
			Profession1:                "Web Developer and Digital Designers",
			Description:                "Web developers membuat dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			DutiesandResponsibilities1: "Bertemu dengan klien atau manajemen untuk mendiskusikan kebutuhan, desain, dan  fungsionalitas situs web atau antarmuka",
			DutiesandResponsibilities2: "Membuat dan menguji aplikasi, antarmuka, dan menu navigasi untuk situs web",
			DutiesandResponsibilities3: "Bekerja dengan desainer grafis dan desainer lain untuk menentukan tata letak situs web",
			DutiesandResponsibilities4: "Merancang dan mengembangkan grafis dan memelihara situs web. Desainer digital mengembangkan, membuat, dan menguji tata letak situs web atau antarmuka, fungsi, dan navigasi untuk kegunaannya.",
			Competition:                "HTML CSS, Javascript Framework, Rest Apis, SQL Server, UI UX, PHP Laravel, Laravel Node, PHP Javascript",
			Subject:                    "Pemrograman Web Lanjut",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESTJ",
			Profession1:                "Database Administrators and Architects",
			Description:                "Membuat atau mengatur sistem untuk menyimpan dan mengamankan berbagai data, seperti informasi keuangan dan catatan pengiriman pelanggan. Memastikan bahwa data tersebut tersedia bagi pengguna yang berwenang.",
			DutiesandResponsibilities1: "Mengidentifikasi kebutuhan pengguna untuk membuat dan mengelola database",
			DutiesandResponsibilities2: "Merancang dan membangun basis data baru",
			DutiesandResponsibilities3: "Membuat dan menguji modifikasi pada struktur basis data bila diperlukan",
			DutiesandResponsibilities4: "Memelihara basis data dan memperbarui izin update",
			Competition:                "Database Administrator, SQL Server, Database Design, Backup Recovery, Backup Restore, Database System, Database Management.",
			Subject:                    "Optimasi Basis Data, Basis Data Lanjut, Sistem Informasi Geografis Energi Ketenagalistrikan",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESTJ",
			Profession2:                "Network and Computer System Administrator",
			Description:                "Bertanggung jawab atas pengoperasian jaringan sehari-hari. Mengatur, memasang, dan mendukung sistem komputer organisasi, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), segmen jaringan, intranet, dan sistem komunikasi data lainnya masalah server komputer.",
			DutiesandResponsibilities1: "Menjaga keamanan jaringan dan sistem komputer",
			DutiesandResponsibilities2: "Mengevaluasi dan mengoptimalkan kinerja jaringan atau sistem",
			DutiesandResponsibilities3: "Melatih pengguna dalam penggunaan perangkat keras dan perangkat lunak yang tepat",
			DutiesandResponsibilities4: "Menafsirkan dan memecahkan masalah ketika pengguna atau sistem pemantauan otomatis memberi tahu mereka bahwa ada masalah",
			Competition:                "Network Engineer, System Administrator, Operate System,  Hardware, Software, Network Administrator, Computer Network, Router Switch, Server Network, System Security",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESTP",
			Profession1:                "Computer Support Specialists",
			Description:                "Membantu pengguna komputer, organisasi, memelihara jaringan komputer atau memberikan bantuan teknis secara langsung kepada pengguna komputer serta menganalisis, memecahkan masalah, dan memelihara jaringan komputer.",
			DutiesandResponsibilities1: "Menguji dan mengevaluasi sistem jaringan yang ada",
			DutiesandResponsibilities2: "Menganalisis masalah komputer pelanggan untuk mendiagnosis dan menentukan penyebabnya",
			DutiesandResponsibilities3: "Mendokumentasikan deskripsi pelanggan tentang masalah komputer mereka",
			DutiesandResponsibilities4: "Memandu pelanggan melalui langkah-langkah pemecahan masalah yang direkomendasikan",
			Competition:                "Hardware, Software, Technical Support, Application Support, Computer System, Computer Hardware, Computer Net, Lan Wan, Net Problem, Installation Configuration, Education Computer",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESTP",
			Profession2:                "Network and Computer System Administrator",
			Description:                "Bertanggung jawab atas pengoperasian jaringan sehari-hari. Mengatur, memasang, dan mendukung sistem komputer organisasi, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), segmen jaringan, intranet, dan sistem komunikasi data lainnya masalah server komputer.",
			DutiesandResponsibilities1: "Menjaga keamanan jaringan dan sistem komputer",
			DutiesandResponsibilities2: "Mengevaluasi dan mengoptimalkan kinerja jaringan atau sistem",
			DutiesandResponsibilities3: "Melatih pengguna dalam penggunaan perangkat keras dan perangkat lunak yang tepat",
			DutiesandResponsibilities4: "Menafsirkan dan memecahkan masalah ketika pengguna atau sistem pemantauan otomatis memberi tahu mereka bahwa ada masalah",
			Competition:                "Network Engineer, System Administrator, Operate System,  Hardware, Software, Network Administrator, Computer Network, Router Switch, Server Network, System Security",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESFJ",
			Profession1:                "Network and Computer System Administrator",
			Description:                "Bertanggung jawab atas pengoperasian jaringan sehari-hari. Mengatur, memasang, dan mendukung sistem komputer organisasi, termasuk jaringan area lokal (LAN), jaringan area luas (WAN), segmen jaringan, intranet, dan sistem komunikasi data lainnya masalah server komputer.",
			DutiesandResponsibilities1: "Menjaga keamanan jaringan dan sistem komputer",
			DutiesandResponsibilities2: "Mengevaluasi dan mengoptimalkan kinerja jaringan atau sistem",
			DutiesandResponsibilities3: "Melatih pengguna dalam penggunaan perangkat keras dan perangkat lunak yang tepat",
			DutiesandResponsibilities4: "Menafsirkan dan memecahkan masalah ketika pengguna atau sistem pemantauan otomatis memberi tahu mereka bahwa ada masalah",
			Competition:                "Network Engineer, System Administrator, Operate System,  Hardware, Software, Network Administrator, Computer Network, Router Switch, Server Network, System Security",
			Subject:                    "Pengantar Teknologi Scada",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESFP",
			Profession1:                "Computer System Analysis",
			Description:                "mempelajari sistem prosedur komputer organisasi dan merancang peningkatannya. membantu organisasi beroperasi dengan lebih efisien dan membuat diagram untuk membantu programmer dan arsitek membangun sistem komputer",
			DutiesandResponsibilities1: "Menganalisis biaya dan manfaat sistem TI dan peningkatan untuk membantu manajer memutuskan mana yang akan dipasang, jika ada",
			DutiesandResponsibilities2: "Merancang cara untuk menambahkan fungsionalitas ke sistem komputer yang sudah ada",
			DutiesandResponsibilities3: "Merancang sistem baru dengan mengonfigurasi perangkat keras dan perangkat lunak",
			DutiesandResponsibilities4: "Mengawasi instalasi dan konfigurasi sistem baru dan menyesuaikannya untuk organisasi",
			DutiesandResponsibilities5: "Menguji sistem untuk memastikan bahwa sistem tersebut bekerja seperti yang diharapkan",
			DutiesandResponsibilities6: "Menulis instruksi manual dan melatih pengguna akhir sistem",
			Competition:                "Business Analysis, Data Analysis, Project Management, System Analysis, Analytical Skills, Data Visualization, Agile Project Management",
			Subject:                    "Sistem Informasi Geografis Energi Ketenagalistrikan",
		},
		{
			ID:                         uuid.New().String(),
			TypePerson:                 "ESFP",
			Profession2:                "Computer Support Specialists",
			Description:                "Membantu pengguna komputer, organisasi, memelihara jaringan komputer atau memberikan bantuan teknis secara langsung kepada pengguna komputer serta menganalisis, memecahkan masalah, dan memelihara jaringan komputer.",
			DutiesandResponsibilities1: "Menguji dan mengevaluasi sistem jaringan yang ada",
			DutiesandResponsibilities2: "Menganalisis masalah komputer pelanggan untuk mendiagnosis dan menentukan penyebabnya",
			DutiesandResponsibilities3: "Mendokumentasikan deskripsi pelanggan tentang masalah komputer mereka",
			DutiesandResponsibilities4: "Memandu pelanggan melalui langkah-langkah pemecahan masalah yang direkomendasikan",
			Competition:                "Hardware, Software, Technical Support, Application Support, Computer System, Computer Hardware, Computer Net, Lan Wan, Net Problem, Installation Configuration, Education Computer",
			Subject:                    "Pengantar Teknologi Scada",
		},
	}

	model := &entities.WorkPersonality{}

	return Seed{
		entity: model,
		run: func(db *gorm.DB) (err error) {
			for _, v := range seeds {
				err = db.Create(&v).Error
			}
			return err
		},
	}
}
